sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
cache:
  yarn: true
notifications:
  email: false
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/nglibrary/ngx-choosy.git
  - 'if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
    git checkout master;
    git config push.default current;
  fi'
after_success:
  - 'if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      npm run release;
      npm publish --access=public;
      npm run release-log;
    fi'

branches:
  only:
    - master
    - /^greenkeeper/.*$/
