sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/nglibrary/ngx-choosy.git
cache:
  yarn: true
notifications:
  email: false
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
after_success:
  - git checkout master
  - git config push.default current
  - npm run release
  - npm publish --access=public
  - npm run release-log
branches:
  only:
    - master
    - /^greenkeeper/.*$/
