export const OPTIONS_REFRESHED = 'OPTIONS_REFRESHED';
export const DROPDOWN_OPENED = 'DROPDOWN_OPENED';
export const DROPDOWN_CLOSED = 'DROPDOWN_CLOSED';
export const DROPDOWN_TOGGLED = 'DROPDOWN_TOGGLED';
export const OPTION_SELECTED = 'OPTION_SELECTED';
export const OPTION_DISABLED = 'OPTION_DISABLED';
export const CLEARED_DISABLED_OPTION = 'CLEARED_DISABLED_OPTION';
export const CLEARED_DISABLED_OPTIONS = 'CLEARED_DISABLED_OPTIONS';
export const NEW_OPTION_ADDED = 'NEW_OPTION_ADDED';
export const OPTION_REMOVED = 'OPTION_REMOVED';
export const OPTION_FILTERED = 'OPTION_FILTERED';
export const SELECTED_OPTION_CLEARED = 'SELECTED_OPTION_CLEARED';
export const SELECTED_OPTIONS_CLEARED = 'SELECTED_OPTIONS_CLEARED';
export const OPTION_CLICKED = 'OPTION_CLICKED';
export const OPTIONS_RESET = 'OPTIONS_RESET';
export const OPTIONS_RELOADED = 'OPTIONS_RELOADED';

export const FOOTER_DEFAULT = 'FOOTER_DEFAULT';
export const FOOTER_FILTER = 'FOOTER_FILTER';
export const FOOTER_INITIAL = 'FOOTER_INITIAL';


export const MSG_NO_OPTIONS = 'No options provided!';
export const ERR_INVALID_OPTIONS = 'No options provided!';
